### ISSUE TITLE
Doesn't work with truffle-config.js

### ISSUE THREAD

**Issue by dmdque** [alcuadrado/truffle-flattener#17]
When running `truffle-flattener`, in a project with `truffle-config.js`, I get:

    TypeError: Cannot read property 'substring' of null
        at getDirPath (/usr/local/lib/node_modules/truffle-flattener/index.js:38:19)
        at getTruffleRoot (/usr/local/lib/node_modules/truffle-flattener/index.js:213:10)
        at <anonymous> 'TypeError: Cannot read property \'substring\' of null\n    at getDirPath (/usr/local/lib/node_modules/truffle-flattener/index.js:38:19)\n    at getTruffleRoot (/usr/local/lib/node_modules/truffle-flattener/index.js:213:10)\n    at <anonymous>'

I'm able to get it to work with `mv truffle-config.js truffle.js`, but it seems something isn't working as intended.

**Comment by ihordiachenko** [comment]
Package v.1.2.4 has the same issue on macOS.
