### ISSUE TITLE
SyntaxError: Unexpected token function

### ISSUE THREAD

**Issue by ccomeon** [alcuadrado/truffle-flattener#4]
Using the suggested install approach and got the following error when trying to flatten a single sol file:

```
/usr/lib/node_modules/truffle-flattener/index.js:65
async function dependenciesDfs(graph, visitedFiles, filePath) {
      ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9)
```

**Comment by alcuadrado** [comment]
Hi Kevin,

Which version of node are you using? You need 7.6+ to run it.

**Comment by ccomeon** [comment]
Hey @alcuadrado!  Thanks for your answer! 
I'm running on LTS 6.x and didn't notice it needs 7.6+ to run. 
It works now after I use the latest stable version(9.1.0).
