### ISSUE TITLE
Error thrown when using Truffle Flattener

### ISSUE THREAD

**Issue by tomasienrbc** [alcuadrado/truffle-flattener#7]
I'm excited about this project, but when I and my co-worker try to use it we get this error: 

truffle-flattener RareToken.sol
/Users/tommy/.nvm/versions/node/v6.0.0/lib/node_modules/truffle-flattener/index.js:65
async function dependenciesDfs(graph, visitedFiles, filePath) {
      ^^^^^^^^
SyntaxError: Unexpected token function
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:511:25)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:159:18)
    at node.js:444:3

Even running "truffle-flattener -v" or any truffle-flattener code throws this error. 

Any ideas?

**Comment by tomasienrbc** [comment]
After sending this I immediately started to think it's probably node version problem - which version are you expecting users to be on?

**Comment by tomasienrbc** [comment]
Yes indeed - I have new issue I'll file but this was solved by upgrading to Node 8
